name: Lumina CI

on:
  push:
    branches:
      - main
      - Dev
  pull_request:
    branches:
      - main
      - Dev
  workflow_dispatch:

jobs:
  validate_and_build:
    name: Validate & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.15.8"

      - name: Terraform Format Check
        run: terraform -chdir=terraform fmt -check

      - name: Terraform init
        run: terraform -chdir=terraform init

      - name: Terraform Validate
        run: terraform -chdir=terraform validate
